name = "bikepowell-api"
main = "worker.js"
compatibility_date = "2024-01-01"

# KV namespace binding
# After you run `wrangler kv:namespace create BUSINESSES`,
# replace the placeholder id below with the real one from the output.
[[kv_namespaces]]
binding = "BUSINESSES"
id = "e94b82513d04465082738dad187e03cb"
